// English translations
window.translations.en = {
    "Business Setup in Dubai, Company Formation in the UAE": "Business Setup in Dubai for Irish Entrepreneurs, Company Formation in UAE",
    "Starting from 5,750 AED | Guaranteed bank account": "Starting from 5,500 AED | Registration 1 day | Guaranteed bank account for Irish Citizens",
    "Get a Free Consultation": "Get a Free Consultation",
    "Our Services": "Our Services",
    "Company Formation": "Company Formation",
    "Free Zone Setup": "Free Zone Setup",
    "Mainland Company Setup": "Mainland Company Setup",
    "Offshore Company Setup": "Offshore Company Setup",
    "Visa Services": "Visa Services",
    "Bank Account Opening": "Bank Account Opening",
    "Learn More": "Learn More",
    "Fill out the form to contact an expert": "Fill out the form to contact an expert",
    "Your Name": "Your Name",
    "Your Email": "Your Email",
    "Your Phone Number": "Your Phone Number",
    "Your Message": "Your Message",
    "Submit": "Submit",
    "UAE Business Setup Process": "UAE Business Setup Process",
    "Learn about the essential steps to establish your company in the UAE": "Learn about the essential steps to establish your company in the UAE",
    "Choose the correct activity": "Choose the correct activity",
    "The choice of license will depend on your business specific needs and the business activities you will be conducting.": "The choice of license will depend on your business specific needs and the business activities you will be conducting.",
    "Decide on the place of registration": "Decide on the place of registration",
    "There are 3 main jurisdictions in the UAE: Mainland, Free zone, Offshore.": "There are 3 main jurisdictions in the UAE: Mainland, Free zone, Offshore.",
    "Get a list of requirements and approvals": "Get a list of requirements and approvals",
    "Depending on your business, obtaining special licenses and permissions from the relevant Emirates authorities may be required.": "Depending on your business, obtaining special licenses and permissions from the relevant Emirates authorities may be required.",
    "Register your company and get the visa": "Register your company and get the visa",
    "Apply for company registration, pay the fees, and obtain the visa and work permits for you and your employees.": "Apply for company registration, pay the fees, and obtain the visa and work permits for you and your employees.",
    "Open a bank account": "Open a bank account",
    "Once you have all the incorporation documents in hand, apply for personal or corporate bank accounts and get started!": "Once you have all the incorporation documents in hand, apply for personal or corporate bank accounts and get started!",
    "Start your business in the UAE free zones": "Start your business in the UAE free zones",
    "There are over 40 different freezones in the UAE to match all business needs": "There are over 40 different freezones in the UAE to match all business needs",
    "DMCC": "DMCC",
    "Dubai Multi Commodities Center": "Dubai Multi Commodities Center",
    "Dubai South Free Zone": "Dubai South Free Zone",
    "(ex. DWC)": "(ex. DWC)",
    "DTEC": "DTEC",
    "Dubai Technology Entrepreneur Center": "Dubai Technology Entrepreneur Center",
    "DAFZA": "DAFZA",
    "Dubai Airport Free Zone": "Dubai Airport Free Zone",
    "IFZA": "IFZA",
    "International Free Zone Authority": "International Free Zone Authority",
    "DSO": "DSO",
    "Dubai Silicon Oasis": "Dubai Silicon Oasis",
    "UAE TAXes": "UAE TAXes",
    "Find out essential details on UAE tax regulations": "Find out essential details on UAE tax regulations",
    "Corporate tax 9%": "Corporate tax 9%",
    "Corporate tax in the UAE is just 9%. All UAE companies need to register with the FTA and submit annual tax returns.": "Corporate tax in the UAE is just 9%. All UAE companies need to register with the FTA and submit annual tax returns.",
    "VAT": "VAT",
    "VAT in the UAE is one of the world's lowest - only 5%. Businesses with an annual revenue exceeding 375,000 AED are required to register for VAT with the FTA.": "VAT in the UAE is one of the world's lowest - only 5%. Businesses with an annual revenue exceeding 375,000 AED are required to register for VAT with the FTA.",
    "Zero personal TAX // Exemption certificate": "Zero personal TAX // Exemption certificate",
    "There is no personal income tax in the UAE, maintaining the country's appeal as a tax-friendly environment for individuals.": "There is no personal income tax in the UAE, maintaining the country's appeal as a tax-friendly environment for individuals.",
    "Dubai trade license": "Dubai trade license",
    "Compare the available business licenses and choose the one matching your needs": "Compare the available business licenses and choose the one matching your needs",
    "E-commerce license": "E-commerce license",
    "Transform your digital business ideas into reality with an E-Commerce License in the UAE": "Transform your digital business ideas into reality with an E-Commerce License in the UAE",
    "Beauty salon license": "Beauty salon license",
    "Embark on a beauty entrepreneur journey in the UAE by obtaining a Beauty Salon License": "Embark on a beauty entrepreneur journey in the UAE by obtaining a Beauty Salon License",
    "Car lease license": "Car lease license",
    "Enter the automotive market with a Car Lease License in the UAE, providing flexible and reliable vehicle leasing options.": "Enter the automotive market with a Car Lease License in the UAE, providing flexible and reliable vehicle leasing options.",
    "Become the UAE resident": "Become the UAE resident",
    "Apply for the UAE residence visa and enjoy all the benefits": "Apply for the UAE residence visa and enjoy all the benefits",
    "Golden visa": "Golden visa",
    "Prestigious 10-year visa": "Prestigious 10-year visa",
    "Real estate investor visa": "Real estate investor visa",
    "Invest in UAE real estate from AED 750,000": "Invest in UAE real estate from AED 750,000",
    "Partner visa": "Partner visa",
    "Elevate your business in the UAE": "Elevate your business in the UAE",
    "Open bank account in the UAE": "Open bank account in the UAE",
    "Learn about bank account types, terms, and requirements": "Learn about bank account types, terms, and requirements",
    "Corporate bank account": "Corporate bank account",
    "Establish a strong financial foundation for your business and grow your business domestically and internationally": "Establish a strong financial foundation for your business and grow your business domestically and internationally",
    "Resident bank account": "Resident bank account",
    "Manage your finances in a stable economic environment, making both local and international transactions with ease": "Manage your finances in a stable economic environment, making both local and international transactions with ease",
    "Non resident account": "Non resident account",
    "Access banking services, conduct financial transactions, and secure your savings without the requirement of residency": "Access banking services, conduct financial transactions, and secure your savings without the requirement of residency",
    "Learn more": "Learn more",
    "Apply now": "Apply now",
    "Watch Our Presentation": "Watch Our Presentation",
    
    // Company Registration Section
    "Company Registration in Dubai": "Company Registration in Dubai - Start Your Business Today",
    "Streamlined Company Registration in Dubai": "Streamlined Company Registration in Dubai",
    "Company Registration Description": "When it comes to company registration in Dubai, Business Setup Solutions has you covered. Our experts will guide you through the process, ensuring your business complies with all local regulations. Let's kickstart your business today!",
    "Company Registration Guide Title": "Company Registration in Dubai – Your Step-by-Step Guide",
    "Company Registration Guide Intro": "Starting a business in Dubai is an exciting venture, but it involves a series of essential steps and compliance with local regulations. At Business Setup Solutions, we simplify the process and guide you through every stage of company registration. Here's a step-by-step guide to help you get started:",
    "Registration Step 1": "Choose the Right Business Activity and Legal Structure",
    "Registration Step 1 Description": "Begin by determining the type of business activity you want to engage in and selecting the appropriate legal structure. We'll help you make the right choices to align with your business goals.",
    "Registration Step 2": "Select a Unique Company Name",
    "Registration Step 2 Description": "Selecting a unique company name is crucial. We'll assist you in choosing a name that complies with Dubai's naming conventions and guidelines.",
    "Registration Step 3": "Prepare the Required Documents",
    "Registration Step 3 Description": "Our experts will guide you in gathering the necessary documents, which may include passports and visa copies of shareholders and directors, a non-objection certificate (NOC) if applicable, and other specific documents depending on your chosen business structure and activity.",
    "Registration Step 4": "Determine Share Capital",
    "Registration Step 4 Description": "Depending on your business structure, you may need to specify the minimum share capital required for your company. We'll ensure you understand the capital requirements.",
    "Registration Step 5": "Obtain Initial Approval",
    "Registration Step 5 Description": "Our team will assist you in applying for initial approval from the relevant government department, such as the Discover Department of Economy and Tourism in Dubai (DED) or the respective Free Zone authority, depending on your chosen business location.",
    "Registration Step 6": "Legalize and Notarize Documents",
    "Registration Step 6 Description": "Certain documents may require notarization and attestation, and we'll help you with this process.",
    "Registration Step 7": "Rent a Physical Office Space",
    "Registration Step 7 Description": "If your business structure requires a physical office, we'll help you find a suitable space that meets the Dubai authorities' requirements.",
    "Registration Step 8": "Submit Documents and Fees",
    "Registration Step 8 Description": "We'll manage the submission of your application, along with the required documents and fees, to the relevant authorities. This may vary based on your chosen business structure and location.",
    "Registration Step 9": "Wait for Approval",
    "Registration Step 9 Description": "While your application is under review, we'll ensure all necessary steps are taken, and you can focus on preparing for your business's exciting launch.",
    "Registration Step 10": "Receive the License",
    "Registration Step 10 Description": "Once your application is approved, you'll receive your business license, granting you the legal right to conduct business in Dubai.",
    "Registration Step 11": "Comply with Ongoing Requirements",
    "Registration Step 11 Description": "Our ongoing support includes helping you renew your business license annually and ensuring you meet all regulatory and financial compliance requirements.",
    "Company Registration Conclusion": "Navigating the process of company registration in Dubai may seem complex, but with the guidance of Business Setup Solutions, it becomes a streamlined and efficient experience. We're your trusted partner in business success, offering expert assistance every step of the way. Start your Dubai business journey with confidence and contact us today for a consultation.",
    
    // Visa Processing Section
    "Dubai Visa Processing Title": "Dubai Visa Processing and PRO Services - Effortless and Efficient",
    "Dubai Visa Processing Subtitle": "Hassle-Free Visa Processing and PRO Services in Dubai",
    "Dubai Visa Processing Description": "Navigating Dubai's visa and government procedures is complex, but our dedicated PRO services team at Business Setup Solutions handles it all, ensuring your business runs smoothly.",
    "Visa Processing Guide Title": "Visa Processing and PRO Services in Dubai – Your Hassle-Free Solution",
    "Visa Processing Guide Intro": "Navigating the complexities of visas and government procedures in Dubai can be challenging. At Business Setup Solutions, we offer expert Visa Processing and PRO (Public Relations Officer) Services to streamline your journey. Here's what you need to know about the process:",
    "Visa Step 1": "Define Your Visa Requirements",
    "Visa Step 1 Description": "The first step is to define your visa requirements, whether it's for yourself or your employees. Our experts will help you understand the type of visa needed, whether it's for employment, family, or other purposes.",
    "Visa Step 2": "Gather Required Documents",
    "Visa Step 2 Description": "We'll provide you with a clear list of required documents, which typically include passport copies, photographs, employment contracts, and other specific documentation based on the type of visa you're applying for.",
    "Visa Step 3": "Visa Application and Submission",
    "Visa Step 3 Description": "Our team will assist you in preparing and submitting your visa application to the relevant government authorities, ensuring that all documents and fees are in order.",
    "Visa Step 4": "Tracking and Follow-Up",
    "Visa Step 4 Description": "We'll keep you informed of the progress of your visa application, including any additional requirements or updates from the authorities.",
    "Visa Step 5": "Visa Issuance and Stamping",
    "Visa Step 5 Description": "Once your visa is approved, we'll guide you through the issuance and stamping process, ensuring that you or your employees are legally allowed to live and work in Dubai.",
    "Visa Step 6": "Renewals and Amendments",
    "Visa Step 6 Description": "Our services extend to visa renewals and amendments, making it easy to keep your documents up to date and compliant with changing circumstances.",
    "Visa Step 7": "PRO Services",
    "Visa Step 7 Description": "Our dedicated PRO team takes care of all your Public Relations Officer needs, including the submission of documents, obtaining permits, and liaising with government authorities on your behalf.",
    "Visa Processing Conclusion": "With Business Setup Solutions, visa processing and PRO services in Dubai become effortless and efficient. We handle the administrative burdens, allowing you to focus on your business operations and personal endeavors. Contact us today to ensure a hassle-free and compliant experience for all your visa and PRO service needs in Dubai.",
    
    // Banking Solutions Section
    "Banking Solutions Title": "Banking Solutions in Dubai - Secure Your Financial Future",
    "Banking Solutions Subtitle": "Comprehensive Banking Solutions Tailored for Your Business",
    "Banking Solutions Description": "Securing your financial future in Dubai is a breeze with our comprehensive banking solutions. Business Setup Solutions is here to guide you through the process of opening business bank accounts and crafting financial strategies that match your unique needs.",
    "Banking Guide Title": "Banking Solutions in Dubai – Secure Your Financial Future",
    "Banking Guide Intro": "Access to the right banking solutions is vital for the financial stability and growth of your business in Dubai. At Business Setup Solutions, we simplify the process and provide expert guidance. Here's what you need to know:",
    "Banking Step 1": "Determine Your Business Banking Needs",
    "Banking Step 1 Description": "The first step is to assess your business's financial needs. Are you looking for business accounts, financing options, or investment services? We'll help you understand the most suitable banking solutions.",
    "Banking Step 2": "Choose the Right Bank",
    "Banking Step 2 Description": "Dubai offers a wide range of banks, each with its strengths and specialties. We'll assist you in selecting the right bank that aligns with your business objectives.",
    "Banking Step 3": "Prepare the Required Documentation",
    "Banking Step 3 Description": "Our experts will provide you with a checklist of documents required for opening a business bank account, which may include legal entity documents, business licenses, and personal identification documents.",
    "Banking Step 4": "Account Opening",
    "Banking Step 4 Description": "We'll guide you through the account opening process, ensuring that all necessary documents are correctly prepared and submitted to the bank.",
    "Banking Step 5": "Financial Strategy and Investment",
    "Banking Step 5 Description": "Our services extend beyond account opening. We provide guidance on financial strategies, investment opportunities, and wealth management to help you make the most of your financial resources.",
    "Banking Step 6": "Loan and Financing Assistance",
    "Banking Step 6 Description": "If you require loans or financing, we'll connect you with the right financial institutions and assist in the application process.",
    "Banking Step 7": "Banking Compliance",
    "Banking Step 7 Description": "Staying compliant with banking regulations is essential. We ensure that your financial transactions and accounts are in accordance with local laws.",
    "Banking Solutions Conclusion": "With Business Setup Solutions, securing your financial future in Dubai becomes a straightforward and well-informed process. We make banking easy and efficient, so you can focus on growing your business and achieving your financial goals. Contact us today to get started with the right banking solutions tailored to your needs.",
    
    // Immigration Services Section
    "Immigration Services Title": "Immigration Services in Dubai - Making Relocation Effortless",
    "Immigration Services Description": "Whether you're an individual looking to relocate to Dubai or a business in need of immigration support for your employees, Business Setup Solutions offers comprehensive Immigration Services to ensure a smooth and efficient process. Here's what you need to know:",
    "Immigration Individual Title": "For Individuals",
    "Immigration Individual Step 1": "Determine Your Visa Type",
    "Immigration Individual Step 1 Description": "The first step for individuals is to determine the type of visa that aligns with your purpose for relocating to Dubai. This could be for employment, family reunion, retirement, or investment, among other options.",
    "Immigration Individual Step 2": "Prepare Required Documents",
    "Immigration Individual Step 2 Description": "Our experts will provide you with a checklist of documents, such as passport copies, educational certificates, marriage certificates, and other documentation specific to your visa category.",
    "Immigration Individual Step 3": "Visa Application and Submission",
    "Immigration Individual Step 3 Description": "We'll guide you through the visa application process and assist in the submission of documents to the relevant authorities.",
    "Immigration Individual Step 4": "Visa Issuance and Stamping",
    "Immigration Individual Step 4 Description": "Once your visa is approved, we'll help you with the visa issuance and stamping process, ensuring you have the legal right to reside and work in Dubai.",
    "Immigration Individual Step 5": "Post-Arrival Services",
    "Immigration Individual Step 5 Description": "Our services extend to post-arrival support, helping you with services like local registration, Emirates ID applications, and other important steps to make your transition to Dubai seamless.",
    "Immigration Business Title": "For Businesses",
    "Immigration Business Step 1": "Employee Immigration",
    "Immigration Business Step 1 Description": "If you're a business looking to bring employees to Dubai, we assist with the immigration of your workforce. This includes visa sponsorship, permits, and compliance with local employment regulations.",
    "Immigration Business Step 2": "Investor Visas",
    "Immigration Business Step 2 Description": "Our experts help investors and entrepreneurs navigate the process of securing investor visas, guiding you through the required documentation and investment thresholds.",
    "Immigration Business Step 3": "Compliance and Renewals",
    "Immigration Business Step 3 Description": "We ensure ongoing compliance with immigration regulations and assist in the renewal of visas and permits.",
    "Immigration Business Step 4": "Corporate Relocation Services",
    "Immigration Business Step 4 Description": "For corporate relocations, we offer comprehensive support, including setting up accommodation, local orientation, and other essential services for relocating employees.",
    "Immigration Services Conclusion": "With Business Setup Solutions, you can be confident that your immigration process in Dubai is handled efficiently and with the utmost professionalism. We take care of all the details, so you can focus on your personal or business success in this dynamic city. Contact us today to make your relocation to Dubai a hassle-free experience.",
    
    // Co-Working Space Section
    "Coworking Title": "Co-Working Space/Private Office",
    "Coworking Subtitle": "Elevate Your Work Experience – Co-Working and Private Offices",
    "Coworking Description": "The perfect workspace is the cornerstone of productivity. Business Setup Solutions offers modern co-working spaces and private offices in prime Dubai locations, fostering a collaborative and professional work environment.",
    "Coworking Guide Title": "Co-Working Space and Private Office Solutions in Dubai – Elevate Your Work Experience",
    "Coworking Guide Intro": "Finding the perfect workspace is a cornerstone of productivity. For you we offer modern and flexible Co-Working Spaces and Private Offices in prime Dubai locations. Here's how you can secure your ideal workspace:",
    "Coworking Spaces Title": "For Co-Working Spaces",
    "Coworking Step 1": "Define Your Workspace Needs",
    "Coworking Step 1 Description": "The first step is to define your workspace requirements. Determine how many workstations you need and what additional amenities and services are essential for your team.",
    "Coworking Step 2": "Choose Your Location",
    "Coworking Step 2 Description": "Dubai offers a variety of vibrant and convenient locations for co-working spaces. We'll help you select the right location that suits your business goals and convenience.",
    "Coworking Step 3": "Select Your Package",
    "Coworking Step 3 Description": "We offer flexible co-working packages, including options for dedicated desks, shared workspaces, and virtual office services. Choose the package that aligns with your needs.",
    "Coworking Step 4": "Book Your Space",
    "Coworking Step 4 Description": "Reserve your co-working space through our user-friendly platform. Our team will guide you through the booking process, ensuring a smooth experience.",
    "Private Office Title": "For Private Offices",
    "Private Office Step 1": "Define Your Office Space Needs",
    "Private Office Step 1 Description": "If you require a private office, we'll work with you to understand your specific requirements, such as the number of employees, office size, and additional amenities.",
    "Private Office Step 2": "Choose Your Location",
    "Private Office Step 2 Description": "Select the location that best suits your business. Dubai offers a diverse range of private office spaces, each with unique advantages.",
    "Private Office Step 3": "Customize Your Office",
    "Private Office Step 3 Description": "We can help you customize your private office space to meet your branding and functional needs.",
    "Private Office Step 4": "Lease Your Private Office",
    "Private Office Step 4 Description": "Our team will guide you through the leasing process, ensuring that all documents and legal requirements are in order.",
    "Additional Services Title": "Additional Services",
    "Business Center Amenities Title": "Business Center Amenities",
    "Business Center Amenities Description": "Access to business center amenities, such as high-speed internet, meeting rooms, reception services, and administrative support, is available to enhance your workspace experience.",
    "Networking Opportunities Title": "Networking Opportunities",
    "Networking Opportunities Description": "Enjoy networking opportunities with like-minded professionals and businesses within the co-working community.",
    "Coworking Conclusion": "With Business Setup Solutions, finding your ideal co-working space or private office in Dubai is effortless. We provide flexible, fully-equipped workspaces that cater to your unique business requirements. Contact us today to elevate your work experience in the heart of Dubai's vibrant business community.",
    
    // VAT and Audit Section
    "VAT Audit Title": "VAT Registration and Annual Audit Services in Dubai",
    "VAT Audit Subtitle": "Stay Compliant – VAT and Annual Audit Services in Dubai",
    "VAT Audit Description": "Staying compliant with VAT regulations is imperative for your Dubai business. Our experts will assist with VAT registration and provide comprehensive annual audit services, keeping your business in good standing.",
    "VAT Audit Guide Title": "VAT and Annual Audit Services in Dubai – Stay Compliant and Informed",
    "VAT Audit Guide Intro": "Compliance with VAT regulations and annual audits are crucial for your business in Dubai. At Business Setup Solutions, we offer expert VAT and Annual Audit Services to ensure your business remains in good standing. Here's how you can benefit from our services:",
    "VAT Registration Title": "VAT Registration",
    "VAT Step 1": "Assess Your VAT Obligations",
    "VAT Step 1 Description": "The first step is to assess your VAT obligations. We help you understand whether your business needs to register for VAT in Dubai.",
    "VAT Step 2": "Gather Required Documentation",
    "VAT Step 2 Description": "We'll guide you through the process of collecting the necessary documentation, which may include financial records, business licenses, and other relevant paperwork.",
    "VAT Step 3": "VAT Registration Application",
    "VAT Step 3 Description": "Our experts will assist you in completing and submitting your VAT registration application to the Federal Tax Authority (FTA).",
    "VAT Step 4": "Compliance and Reporting",
    "VAT Step 4 Description": "Once registered, we'll ensure that you stay compliant with VAT regulations, guiding you on proper invoicing, record-keeping, and timely tax reporting.",
    "Annual Audit Title": "Annual Audit Services",
    "Audit Step 1": "Assess Your Audit Needs",
    "Audit Step 1 Description": "Understanding your specific audit requirements is the first step. Depending on the size and nature of your business, you may be required to undergo annual financial audits.",
    "Audit Step 2": "Choose an Audit Firm",
    "Audit Step 2 Description": "We can help you select a reputable audit firm with expertise in your industry.",
    "Audit Step 3": "Prepare Financial Records",
    "Audit Step 3 Description": "Our team will assist you in preparing your financial records and documents for the audit, ensuring that you are well-prepared for the process.",
    "Audit Step 4": "Audit Process",
    "Audit Step 4 Description": "We'll coordinate with the chosen audit firm to ensure a smooth and efficient audit process. We'll also guide you through any required adjustments or improvements in your financial systems.",
    "Audit Step 5": "Audit Reporting",
    "Audit Step 5 Description": "We provide support in the preparation of audit reports and the submission of the necessary documents to regulatory authorities.",
    "VAT Audit Conclusion": "With Business Setup Solutions, VAT registration and annual audit services in Dubai are simplified and efficient. We'll ensure your business is compliant with tax regulations and financially sound. Contact us today to stay on top of your VAT and annual audit requirements, giving you peace of mind and time to focus on your core business activities.",
    
    // Corporate Advisory Section
    "Corporate Advisory Title": "Strategic Corporate Advisory Services in Dubai",
    "Corporate Advisory Subtitle": "Navigate Market Complexities with Our Corporate Advisory Services",
    "Corporate Advisory Description": "Rely on Business Setup Solutions for strategic business decisions. Our corporate advisory services offer customized strategies for navigating market complexities and achieving business goals.",
    "Corporate Advisory Guide Title": "Corporate Advisory Services in Dubai – Navigating Market Complexities with Confidence",
    "Corporate Advisory Guide Intro": "For informed business decisions and strategic planning, turn to Business Setup Solutions. Our Corporate Advisory Services offer expert guidance tailored to your unique business objectives. Here's how you can benefit from our advisory services:",
    "Company Formation Intro": "Navigating the complexities of setting up a business in a new country can be a daunting task. At Business Setup Solutions Dubai, we simplify the entire process, providing you with end-to-end support to get your company up and running in the UAE. Our team of experienced consultants will work closely with you to understand your business needs and recommend the most suitable legal structure, whether it's a mainland, free zone, or offshore company.",
    "CF Benefit 1": "Expert guidance on choosing the right business jurisdiction.",
    "CF Benefit 2": "Hassle-free handling of all paperwork and legal formalities.",
    "CF Benefit 3": "Assistance with opening corporate bank accounts.",
    "CF Benefit 4": "Full compliance with all UAE laws and regulations.",
    "Company Formation Process": "We handle all the paperwork, from trade name reservation and initial approval to the final submission of your application, ensuring that you are fully compliant with all local regulations. With our expert guidance, you can be confident that your company formation process will be smooth, efficient, and hassle-free, allowing you to focus on what you do best—growing your business.",
    "Free Zone Setup Intro": "The UAE is home to over 40 free zones, each offering a unique set of benefits and incentives for businesses. Our Free Zone Setup services are designed to help you navigate this landscape and choose the free zone that is best suited to your business needs. We provide expert advice on the various free zones, taking into account factors such as your industry, budget, and long-term goals.",
    "FZ Benefit 1": "100% foreign ownership of your business.",
    "FZ Benefit 2": "0% corporate and personal income tax.",
    "FZ Benefit 3": "100% repatriation of profits and capital.",
    "FZ Benefit 4": "Access to a world-class business environment and infrastructure.",
    "Free Zone Process": "Once you have made your decision, we will handle the entire setup process, from preparing the necessary documents to liaising with the free zone authorities. With our assistance, you can take full advantage of the benefits of a free zone company, including 100% foreign ownership, 0% corporate and personal income tax, and 100% repatriation of profits and capital.",
    "Mainland Company Setup Intro": "For businesses looking to operate within the UAE's local market, a mainland company is the ideal choice. Our Mainland Company Setup services provide you with a seamless and efficient way to establish your presence in the heart of the UAE's economy. We will guide you through the entire process, from securing the necessary approvals from the Department of Economic Development (DED) to helping you find a reliable local sponsor.",
    "MC Benefit 1": "Freedom to trade with any company in the UAE.",
    "MC Benefit 2": "Ability to bid on government contracts.",
    "MC Benefit 3": "No restrictions on the number of visas you can apply for.",
    "MC Benefit 4": "Flexibility to operate from any location in the UAE.",
    "Mainland Company Process": "Our team will ensure that your business is fully compliant with all local laws and regulations, giving you the freedom to trade with any company in the UAE and bid on government contracts. With our expert support, you can unlock the full potential of the UAE market.",
    "Offshore Company Setup Intro": "For businesses that operate on a global scale, a UAE offshore company offers a strategic advantage. Our Offshore Company Setup services are designed to help you establish a presence in a stable and reputable jurisdiction, while enjoying the benefits of a tax-efficient corporate structure. We can assist you with the formation of offshore companies in leading jurisdictions such as JAFZA and RAK ICC, providing you with a secure and confidential platform for your international business activities.",
    "OC Benefit 1": "Asset protection and confidentiality.",
    "OC Benefit 2": "Tax optimization and efficiency.",
    "OC Benefit 3": "Access to a stable and reputable jurisdiction.",
    "OC Benefit 4": "Enhanced global competitiveness.",
    "Offshore Company Process": "Our team will manage the entire setup process, ensuring that you are in full compliance with all legal and regulatory requirements. With a UAE offshore company, you can protect your assets, optimize your tax position, and enhance your global competitiveness.",
    "Visa Services Intro": "The UAE's visa system can be complex and time-consuming to navigate. Our Visa Services are designed to simplify the process, providing you with expert guidance and support every step of the way. We offer a wide range of visa services, including employment visas, investor visas, family visas, and tourist visas.",
    "VS Benefit 1": "Expert guidance on all types of UAE visas.",
    "VS Benefit 2": "Assistance with the preparation and submission of all necessary documents.",
    "VS Benefit 3": "Liaison with government authorities on your behalf.",
    "VS Benefit 4": "Timely and successful outcomes for your visa applications.",
    "Visa Services Process": "Our team will assist you with the preparation of all necessary documents, ensuring that your application is complete and accurate. We will also liaise with the relevant government authorities on your behalf, keeping you updated on the status of your application and ensuring a timely and successful outcome. With our help, you can secure your visa with minimal stress and hassle, allowing you to focus on your new life in the UAE.",
    "Bank Account Opening Intro": "A UAE bank account is essential for doing business in the country, but the process of opening one can be complex and time-consuming. Our Bank Account Opening services are designed to make the process as simple and straightforward as possible. We have established strong relationships with the leading banks in the UAE, giving us the ability to fast-track your application and ensure a successful outcome.",
    "BAO Benefit 1": "Access to a wide range of personal and corporate bank accounts.",
    "BAO Benefit 2": "Fast-track application processing.",
    "BAO Benefit 3": "Expert guidance on the required documentation.",
    "BAO Benefit 4": "Assistance with the entire process, from application to activation.",
    "Bank Account Opening Process": "We will assist you with the preparation of all necessary documents, and we will guide you through the entire process, from the initial application to the final activation of your account. Whether you need a personal or a corporate bank account, we can help you find the right solution for your needs.",
    "Residence Visa Intro": "Obtaining a residence visa is a key step for anyone looking to live and work in the UAE. Our Residence Visa services are designed to make this process as smooth and efficient as possible. We provide comprehensive support for a wide range of residence visas, including investor visas, employment visas, and family visas.",
    "RV Benefit 1": "Expert guidance on the different types of residence visas.",
    "RV Benefit 2": "Assistance with the preparation and submission of all necessary documents.",
    "RV Benefit 3": "Full support throughout the entire application process.",
    "RV Benefit 4": "Peace of mind knowing that your application is in expert hands.",
    "Residence Visa Process": "Our team will guide you through the entire application process, from the initial eligibility assessment to the final stamping of your visa. We will ensure that you have all the necessary documents and that your application is submitted in accordance with the latest government regulations. With our expert assistance, you can secure your residence visa with confidence, allowing you to enjoy all the benefits of living in the UAE.",
    "Accounting Support Solutions Intro": "Maintaining accurate and up-to-date financial records is crucial for the success of any business. Our Accounting Support Solutions are designed to provide you with the expert assistance you need to manage your finances effectively. We offer a comprehensive range of accounting services, including bookkeeping, financial statement preparation, and VAT registration and filing.",
    "AS Benefit 1": "Accurate and up-to-date financial records.",
    "AS Benefit 2": "Full compliance with all local regulations.",
    "AS Benefit 3": "Expert advice on VAT and other tax matters.",
    "AS Benefit 4": "Peace of mind knowing that your finances are in expert hands.",
    "Accounting Support Solutions Process": "Our team of qualified accountants will work with you to ensure that your financial records are in order and that you are in full compliance with all local regulations. By outsourcing your accounting needs to us, you can save time and money, and gain the peace of mind that comes with knowing that your finances are in expert hands.",
    "Relocation Services Intro": "Relocating to a new country can be a challenging and overwhelming experience. Our Relocation Services are designed to take the stress out of your move, providing you with comprehensive support to help you and your family settle into your new life in the UAE. We offer a wide range of services, including assistance with finding the perfect home, choosing the right school for your children, and navigating the local healthcare system.",
    "RS Benefit 1": "Personalized and attentive service.",
    "RS Benefit 2": "Assistance with finding accommodation, schools, and healthcare.",
    "RS Benefit 3": "Support with the practical aspects of your move.",
    "RS Benefit 4": "A smooth and enjoyable relocation experience.",
    "Relocation Services Process": "We can also help with the practical aspects of your move, such as setting up bank accounts, obtaining a driver's license, and connecting your utilities. With our personalized and attentive service, we will ensure that your relocation to the UAE is a smooth and enjoyable experience.",
    "Advisory Step 1": "Define Your Business Goals",
    "Advisory Step 1 Description": "Start by defining your business goals and objectives. Whether you're looking to expand, optimize, or restructure your business, we're here to assist.",
    "Advisory Step 2": "Business Assessment",
    "Advisory Step 2 Description": "Our expert team conducts a comprehensive assessment of your business, analyzing its strengths, weaknesses, opportunities, and threats (SWOT analysis).",
    "Advisory Step 3": "Tailored Strategic Plan",
    "Advisory Step 3 Description": "Based on the assessment, we create a customized strategic plan designed to achieve your business objectives. This plan will outline key actions, timelines, and milestones.",
    "Advisory Step 4": "Market Research",
    "Advisory Step 4 Description": "We conduct in-depth market research to help you understand market dynamics, trends, and competitors, ensuring that your strategy is well-informed.",
    "Advisory Step 5": "Financial Analysis",
    "Advisory Step 5 Description": "Our financial experts analyze your financial data, providing insights to optimize your financial performance and investment decisions.",
    "Advisory Step 6": "Regulatory Compliance",
    "Advisory Step 6 Description": "We ensure your business stays compliant with local regulations, offering guidance on any necessary adjustments to remain within the law.",
    "Advisory Step 7": "Implementation Support",
    "Advisory Step 7 Description": "We provide ongoing support during the implementation of your strategic plan, assisting with any challenges that may arise.",
    "Advisory Step 8": "Performance Monitoring",
    "Advisory Step 8 Description": "Our advisory services include performance monitoring to ensure your business stays on track and adapts to changing market conditions.",
    "Additional Advisory Services Title": "Additional Services",
    "MA Service Title": "Mergers and Acquisitions (M&A)",
    "MA Service Description": "If you're considering M&A activities, we offer expert support, from identifying potential targets to due diligence and post-merger integration.",
    "Financial Restructuring Title": "Financial Restructuring",
    "Financial Restructuring Description": "We provide guidance on financial restructuring to optimize your capital structure and enhance financial performance.",
    "Risk Management Title": "Risk Management",
    "Risk Management Description": "Mitigate risks effectively with our risk management services, ensuring your business remains resilient in the face of challenges.",
    "Corporate Advisory Conclusion": "With Business Setup Solutions, you can confidently navigate market complexities and make informed business decisions. Our corporate advisory services are designed to empower your business and maximize opportunities. Contact us today to explore how we can help you achieve your business goals in Dubai and beyond.",

    // Free Zone Pages
    "dmcc_title": "DMCC (Dubai Multi Commodities Centre)",
    "dmcc_intro_heading": "Introduction to DMCC",
    "dmcc_intro_p1": "DMCC is a government entity established in 2002 to enhance commodity trade flows through Dubai. It is the world's most interconnected Free Zone, and the leading trade and enterprise hub for commodities.",
    "dmcc_intro_p2": "DMCC is home to a vibrant community, innovative infrastructure, world-class services and a stunning choice of properties, all of which are designed to help your business thrive.",
    "dmcc_benefits_heading": "Benefits of Setting Up in DMCC",
    "dmcc_benefit1": "100% foreign business ownership",
    "dmcc_benefit2": "0% corporate and personal income tax",
    "dmcc_benefit3": "Strategic location in the heart of new Dubai",
    "dmcc_benefit4": "A full range of business activities",
    "dmcc_benefit5": "World-class infrastructure",
    "dmcc_activities_heading": "Business Activities in DMCC",
    "dmcc_activities_p1": "DMCC offers a wide range of business activities, including trading, services, and industrial activities. Whether you are a startup or a multinational corporation, DMCC has a solution for you.",
    "dmcc_formation_heading": "Company Formation Process",
    "dmcc_formation_p1": "The company formation process in DMCC is straightforward and can be completed in a few weeks. Our team will guide you through every step, from initial application to receiving your business license.",

    "ifza_title": "IFZA (International Free Zone Authority)",
    "ifza_intro_heading": "Introduction to IFZA",
    "ifza_intro_p1": "IFZA is one of the most affordable and fastest-growing free zones in the UAE. It offers a wide range of business activities and license types, making it an ideal choice for startups and SMEs.",
    "ifza_intro_p2": "Located in Dubai, IFZA provides a highly competitive and business-friendly environment for entrepreneurs from around the world.",
    "ifza_benefits_heading": "Benefits of Setting Up in IFZA",
    "ifza_benefit1": "Cost-effective business setup packages",
    "ifza_benefit2": "Fast and easy company formation",
    "ifza_benefit3": "No physical office requirement",
    "ifza_benefit4": "Wide range of business activities",
    "ifza_benefit5": "100% foreign ownership",
    "ifza_activities_heading": "Business Activities in IFZA",
    "ifza_activities_p1": "IFZA offers a variety of license options, including professional, commercial, and industrial licenses. This flexibility allows you to conduct a wide range of business activities under one license.",
    "ifza_formation_heading": "Company Formation Process",
    "ifza_formation_p1": "The company formation process in IFZA is designed to be quick and efficient. With our assistance, you can have your company registered and licensed in just a few days.",

    "difc_title": "DIFC (Dubai International Financial Centre)",
    "difc_intro_heading": "Introduction to DIFC",
    "difc_intro_p1": "DIFC is the leading financial hub for the Middle East, Africa and South Asia (MEASA) region. It has its own independent, internationally regulated regulator and judicial system, common law framework, global financial exchange, tax-friendly regime, and a large business community.",
    "difc_benefits_heading": "Benefits of Setting Up in DIFC",
    "difc_benefit1": "Independent legal and regulatory framework",
    "difc_benefit2": "100% foreign ownership",
    "difc_benefit3": "0% tax on income and profits for 50 years",
    "difc_benefit4": "Access to a deep pool of skilled professionals",
    "difc_benefit5": "A vibrant ecosystem of financial and non-financial companies",
    "difc_activities_heading": "Business Activities in DIFC",
    "difc_activities_p1": "DIFC is the ideal base for financial and professional services firms. It offers licenses for banking, insurance, wealth management, and capital markets, as well as non-financial activities such as consulting and legal services.",
    "difc_formation_heading": "Company Formation Process",
    "difc_formation_p1": "The company formation process in DIFC is rigorous to ensure the highest standards of quality and compliance. Our team has the expertise to navigate the process and help you establish your presence in this prestigious financial centre.",

    "jafza_title": "JAFZA (Jebel Ali Free Zone)",
    "jafza_intro_heading": "Introduction to JAFZA",
    "jafza_intro_p1": "JAFZA is one of the world's largest free zones and a leading hub for trade and logistics. Located next to the Jebel Ali Port, the world's ninth busiest port, and Al Maktoum International Airport, JAFZA offers unparalleled connectivity to global markets.",
    "jafza_benefits_heading": "Benefits of Setting Up in JAFZA",
    "jafza_benefit1": "Unrivalled access to global markets",
    "jafza_benefit2": "100% foreign ownership",
    "jafza_benefit3": "0% import or re-export duties",
    "jafza_benefit4": "No currency restrictions",
    "jafza_benefit5": "On-site customs facilities",
    "jafza_activities_heading": "Business Activities in JAFZA",
    "jafza_activities_p1": "JAFZA is ideal for companies in the logistics, manufacturing, and trading sectors. It offers a wide range of licenses and facilities, including warehouses, offices, and industrial land.",
    "jafza_formation_heading": "Company Formation Process",
    "jafza_formation_p1": "Setting up a company in JAFZA involves a comprehensive process to ensure compliance with its high standards. Our team will manage the entire process for you, from document submission to license issuance.",

    "dafza_title": "DAFZA (Dubai Airport Free Zone)",
    "dafza_intro_heading": "Introduction to DAFZA",
    "dafza_intro_p1": "DAFZA is one of the most prestigious and advanced free zones in the world. Located adjacent to Dubai International Airport, it offers a gateway to the Middle East and unparalleled access to global markets.",
    "dafza_benefits_heading": "Benefits of Setting Up in DAFZA",
    "dafza_benefit1": "Direct access to Dubai International Airport",
    "dafza_benefit2": "State-of-the-art infrastructure and facilities",
    "dafza_benefit3": "24/7 customs services and rapid cargo clearance",
    "dafza_benefit4": "A dedicated government service center",
    "dafza_benefit5": "100% foreign ownership",
    "dafza_activities_heading": "Business Activities in DAFZA",
    "dafza_activities_p1": "DAFZA is ideal for businesses in sectors such as aviation, logistics, pharmaceuticals, IT, and luxury goods. It offers a range of licenses, including trade, service, and industrial licenses.",
    "dafza_formation_heading": "Company Formation Process",
    "dafza_formation_p1": "The company formation process in DAFZA is streamlined and efficient. Our team will assist you with every step, ensuring a smooth and hassle-free setup experience.",

    "rakez_title": "RAKEZ (Ras Al Khaimah Economic Zone)",
    "rakez_intro_heading": "Introduction to RAKEZ",
    "rakez_intro_p1": "RAKEZ is a powerhouse business and industrial hub in the UAE that offers customised solutions to free zone and non-free zone businesses. From freelancers and startups to SMEs and industrialists, RAKEZ has a solution for every type of business.",
    "rakez_benefits_heading": "Benefits of Setting Up in RAKEZ",
    "rakez_benefit1": "Cost-effective business setup packages",
    "rakez_benefit2": "Wide range of industrial and commercial facilities",
    "rakez_benefit3": "Easy access to major logistical hubs",
    "rakez_benefit4": "A one-stop shop for all government services",
    "rakez_benefit5": "100% foreign ownership",
    "rakez_activities_heading": "Business Activities in RAKEZ",
    "rakez_activities_p1": "RAKEZ caters to a diverse range of industries, including manufacturing, trading, services, and education. It offers over 100 business activities and a variety of license types to suit your needs.",
    "rakez_formation_heading": "Company Formation Process",
    "rakez_formation_p1": "The company formation process in RAKEZ is simple and straightforward. Our team will assist you with the entire process, from choosing the right license to obtaining your visa.",

    // Corporate Tax Page
    "corporate_tax_title": "Understanding UAE Corporate Tax",
    "corporate_tax_intro_heading": "Introduction to the 9% Corporate Tax Rate",
    "corporate_tax_intro_p1": "The UAE introduced a federal corporate tax with a standard rate of 9%, effective from June 2023. This is a significant development for all businesses operating in the UAE, including those owned by Irish entrepreneurs. While this rate is still highly competitive globally, it requires careful planning and compliance.",
    "corporate_tax_intro_p2": "At Business Setup Solutions Dubai, we specialize in helping Irish businesses navigate this new tax landscape, ensuring full compliance while optimizing your financial strategy.",
    "corporate_tax_compliance_heading": "Key Compliance Requirements for Irish Businesses",
    "corporate_tax_compliance1": "<strong>FTA Registration:</strong> All businesses in the UAE, including those in free zones, must register with the Federal Tax Authority (FTA).",
    "corporate_tax_compliance2": "<strong>Annual Tax Returns:</strong> Companies are required to file an annual corporate tax return with the FTA.",
    "corporate_tax_compliance3": "<strong>Financial Records:</strong> Maintaining accurate and audited financial statements is mandatory for tax purposes.",
    "corporate_tax_compliance4": "<strong>Transfer Pricing:</strong> Businesses with international transactions, such as those with a parent company in Ireland, must comply with transfer pricing regulations.",
    "corporate_tax_freezone_heading": "Corporate Tax in UAE Free Zones",
    "corporate_tax_freezone_p1": "While free zones have historically offered a zero-tax environment, the new corporate tax law applies to them as well. However, 'Qualifying Free Zone Persons' can still benefit from a 0% tax rate on 'Qualifying Income'. Our experts can help you determine if your business qualifies and assist you in meeting the specific requirements.",
    "corporate_tax_assistance_heading": "How We Can Assist You",
    "corporate_tax_assistance_p1": "Our team provides end-to-end support for Irish businesses dealing with UAE corporate tax. From initial registration with the FTA to strategic tax planning and filing of annual returns, we ensure your business remains compliant and efficient. Contact us today for a consultation.",

    // VAT Page
    "vat_title": "Understanding VAT in the UAE",
    "vat_intro_heading": "The 5% VAT Rate Explained",
    "vat_intro_p1": "Value Added Tax (VAT) was introduced in the UAE in 2018 at a standard rate of 5%. This is one of the lowest VAT rates in the world, but it applies to most goods and services. For Irish businesses operating in Dubai, understanding your VAT obligations is essential for compliance and smooth operations.",
    "vat_intro_p2": "Our team at Business Setup Solutions Dubai provides clear, practical advice to help Irish entrepreneurs manage their VAT responsibilities effectively.",
    "vat_registration_heading": "VAT Registration for Irish Businesses",
    "vat_registration1": "<strong>Mandatory Registration:</strong> If your business's annual revenue exceeds AED 375,000, you are required to register for VAT with the Federal Tax Authority (FTA).",
    "vat_registration2": "<strong>Voluntary Registration:</strong> If your annual revenue is between AED 187,500 and AED 375,000, you have the option to register for VAT voluntarily.",
    "vat_registration3": "<strong>Required Documents:</strong> We can assist you in preparing the necessary documents for registration, including your trade license and passport copies.",
    "vat_compliance_heading": "Ongoing VAT Compliance",
    "vat_compliance_p1": "VAT compliance involves more than just registration. Businesses must issue tax-compliant invoices, keep detailed financial records, and file regular VAT returns with the FTA. Failure to comply can result in significant penalties. We offer comprehensive accounting and bookkeeping services to ensure you meet all your VAT obligations.",
    "vat_assistance_heading": "How We Can Help with VAT",
    "vat_assistance_p1": "From determining if you need to register for VAT to handling your periodic filings, our experts are here to help. We provide tailored VAT solutions for Irish businesses in Dubai, allowing you to focus on growth while we handle the complexities of tax compliance. Get in touch with us to learn more.",

    // Zero Personal Tax Page
    "personal_tax_title": "Zero Personal Tax in the UAE",
    "personal_tax_intro_heading": "A Major Benefit for Irish Expats",
    "personal_tax_intro_p1": "One of the most significant advantages of living and working in the UAE is the absence of personal income tax. This means that as an Irish expatriate, your salary and other personal income earned in the UAE are not subject to any local income tax, allowing for greater savings and disposable income.",
    "personal_tax_intro_p2": "This tax-friendly environment is a key reason why so many Irish professionals and entrepreneurs choose to relocate to Dubai and other Emirates.",
    "personal_tax_certificate_heading": "Tax Residency Certificate for Irish Citizens",
    "personal_tax_certificate1": "<strong>Purpose:</strong> A Tax Residency Certificate (TRC) can be crucial for Irish citizens to prove their tax residency in the UAE and potentially avoid tax liabilities in Ireland on their UAE-sourced income, subject to the Ireland-UAE Double Taxation Treaty.",
    "personal_tax_certificate2": "<strong>Eligibility:</strong> To be eligible for a TRC, you generally need to have been a resident in the UAE for at least 180 days and have a valid residence visa.",
    "personal_tax_certificate3": "<strong>Application Process:</strong> The application is made through the Federal Tax Authority (FTA) portal. We can guide you through the process and help you gather the required documentation.",
    "personal_tax_implications_heading": "Implications for Your Business",
    "personal_tax_implications_p1": "For Irish entrepreneurs, the zero personal tax regime means you can extract profits from your UAE company as dividends or salary without incurring any personal income tax in the UAE. This creates a highly efficient structure for wealth accumulation.",
    "personal_tax_assistance_heading": "Our Expert Guidance",
    "personal_tax_assistance_p1": "Understanding the nuances of international tax treaties can be complex. Business Setup Solutions Dubai provides expert advice on how to structure your affairs to take full advantage of the UAE's tax benefits while remaining compliant with Irish and international regulations. Contact us to discuss your specific situation.",

    "golden_visa_title": "Golden Visa - UAE Residency | Business Setup Solutions Dubai",
    "golden_visa_description": "Learn about the UAE Golden Visa, a prestigious 10-year residency program for investors, entrepreneurs, and exceptional talents.",
    "golden_visa_program": "Golden Visa Program",
    "golden_visa_intro": "The Golden Visa is a long-term residence visa that allows foreign talents to live, work, or study in the UAE while enjoying exclusive benefits. It is designed for investors, entrepreneurs, scientists, outstanding students, and humanitarian pioneers who have made significant contributions to their field.",
    "golden_visa_key_benefits": "Key Benefits of the Golden Visa",
    "golden_visa_benefit1": "10-year renewable residence visa.",
    "golden_visa_benefit2": "No need for a national sponsor.",
    "golden_visa_benefit3": "Ability to sponsor family members, including spouses and children regardless of their ages.",
    "golden_visa_benefit4": "Sponsorship of an unlimited number of domestic helpers.",
    "golden_visa_benefit5": "Extended visa validity for family members after the death of the primary holder.",
    "golden_visa_eligibility": "Eligibility Criteria",
    "golden_visa_eligibility_intro": "Eligibility for the Golden Visa is determined by the applicant's profession, investment, or talent. The main categories include:",
    "golden_visa_investors": "<strong>Investors:</strong> Public investments of at least AED 2 million.",
    "golden_visa_entrepreneurs": "<strong>Entrepreneurs:</strong> Founder of a project with a capital of at least AED 500,000.",
    "golden_visa_talents": "<strong>Exceptional Talents:</strong> Doctors, scientists, artists, and inventors.",
    "golden_visa_students": "<strong>Outstanding Students:</strong> High-performing students in UAE secondary schools and universities.",

    "real_estate_visa_title": "Real Estate Investor Visa - UAE Residency | Business Setup Solutions Dubai",
    "real_estate_visa_description": "Discover the benefits of the UAE Real Estate Investor Visa, available for individuals who invest in property valued at AED 750,000 or more.",
    "real_estate_visa_heading": "Real Estate Investor Visa",
    "real_estate_visa_intro": "The Real Estate Investor Visa offers a renewable residence visa to individuals who invest in the UAE's property market. This visa is an excellent option for those looking to establish a long-term presence in the country through real estate ownership.",
    "real_estate_visa_key_benefits": "Key Benefits of the Real Estate Investor Visa",
    "real_estate_visa_benefit1": "Renewable residence visa for 2 years.",
    "real_estate_visa_benefit2": "Ability to sponsor your spouse and children.",
    "real_estate_visa_benefit3": "No requirement to establish a company in the UAE.",
    "real_estate_visa_benefit4": "Enjoy the benefits of being a UAE resident, including opening bank accounts.",
    "real_estate_visa_eligibility": "Eligibility Criteria",
    "real_estate_visa_eligibility_intro": "To qualify for the Real Estate Investor Visa, applicants must meet the following criteria:",
    "real_estate_visa_property_value": "<strong>Property Value:</strong> Own a property with a gross value of at least AED 750,000.",
    "real_estate_visa_title_deed": "<strong>Title Deed:</strong> The property must be fully paid for and a title deed must be issued in the applicant's name.",
    "real_estate_visa_freehold": "<strong>Freehold Property:</strong> The property must be located in a freehold area designated for foreign ownership.",

    "partner_visa_title": "Partner Visa - UAE Residency | Business Setup Solutions Dubai",
    "partner_visa_description": "Learn how to obtain a Partner Visa in the UAE by investing in a mainland or free zone company. Secure your residency and grow your business.",
    "partner_visa_heading": "Partner Visa",
    "partner_visa_intro": "A Partner Visa is available to foreign nationals who own shares in an existing mainland or free zone company in the UAE. This visa allows you to live and work in the country, making it an ideal choice for business owners and entrepreneurs looking to elevate their presence in the region.",
    "partner_visa_key_benefits": "Key Benefits of the Partner Visa",
    "partner_visa_benefit1": "Residency in the UAE for the duration of your partnership.",
    "partner_visa_benefit2": "Ability to sponsor your family members.",
    "partner_visa_benefit3": "Full access to UAE banking and healthcare services.",
    "partner_visa_benefit4": "Freedom to travel in and out of the country.",
    "partner_visa_eligibility": "Eligibility Criteria",
    "partner_visa_eligibility_intro": "To be eligible for a Partner Visa, you must meet the following conditions:",
    "partner_visa_shares": "<strong>Company Shares:</strong> Own shares in a UAE-based company with a minimum value of AED 72,000.",
    "partner_visa_medical": "<strong>Medical Fitness:</strong> Pass a medical fitness test at a government-approved health center.",
    "partner_visa_security": "<strong>Security Clearance:</strong> Obtain security clearance from the relevant authorities.",

    // E-Commerce License Page
    "ecommerce_license_title": "E-Commerce License",
    "ecommerce_license_intro": "The UAE's e-commerce market is booming, offering a massive opportunity for Irish entrepreneurs. An E-Commerce license allows you to sell goods and services online, tapping into a dynamic and growing digital economy. We provide end-to-end support to help you launch your online business in Dubai quickly and efficiently.",
    "ecommerce_license_benefits_heading": "Key Benefits",
    "ecommerce_license_benefit1": "Access to the fast-growing UAE and GCC online markets.",
    "ecommerce_license_benefit2": "100% foreign ownership in free zones.",
    "ecommerce_license_benefit3": "Low setup costs and operational overheads.",
    "ecommerce_license_benefit4": "Full compliance with UAE e-commerce regulations.",
    "ecommerce_license_process_heading": "Our Process",
    "ecommerce_license_process_p1": "We handle everything from choosing the right jurisdiction (free zone or mainland) to registering your trade name and obtaining the necessary approvals. Our team ensures your e-commerce business is set up for success, allowing you to focus on building your online brand.",

    // Car Lease License Page
    "car_lease_license_title": "Car Lease License",
    "car_lease_license_intro": "The automotive and tourism sectors in the UAE are thriving, making a car lease or rental business a lucrative venture for Irish investors. A Car Lease license is required to operate this type of business, and we can guide you through the specific requirements and regulations set by the Roads and Transport Authority (RTA).",
    "car_lease_license_benefits_heading": "Key Benefits",
    "car_lease_license_benefit1": "Tap into Dubai's booming tourism and automotive markets.",
    "car_lease_license_benefit2": "High demand for both short-term rentals and long-term leasing.",
    "car_lease_license_benefit3": "Clear regulatory framework under the RTA.",
    "car_lease_license_benefit4": "Full support with fleet registration and insurance.",
    "car_lease_license_process_heading": "Our Process",
    "car_lease_license_process_p1": "We provide comprehensive support for obtaining your Car Lease license. This includes securing initial approval from the RTA, preparing all necessary documentation, and ensuring your business is fully compliant with all transport regulations. Let us handle the paperwork so you can focus on building your fleet."
};
