// English translations
window.translations.en = {
    "Business Setup in Dubai, Company Formation in UAE": "Business Setup in Dubai, Company Formation in UAE",
    "Starting from 5,500 AED | Registration 1 day | Guaranteed bank account": "Starting from 5,500 AED | Registration 1 day | Guaranteed bank account",
    "Get a Free Consultation": "Get a Free Consultation",
    "Our Services": "Our Services",
    "Company Formation": "Company Formation",
    "Free Zone Setup": "Free Zone Setup",
    "Mainland Company Setup": "Mainland Company Setup",
    "Offshore Company Setup": "Offshore Company Setup",
    "Visa Services": "Visa Services",
    "Bank Account Opening": "Bank Account Opening",
    "Learn More": "Learn More",
    "Fill out the form to contact an expert": "Fill out the form to contact an expert",
    "Your Name": "Your Name",
    "Your Email": "Your Email",
    "Your Phone Number": "Your Phone Number",
    "Your Message": "Your Message",
    "Submit": "Submit",
    "UAE Business Setup Process": "UAE Business Setup Process",
    "Learn about the essential steps to establish your company in the UAE": "Learn about the essential steps to establish your company in the UAE",
    "Choose the correct activity": "Choose the correct activity",
    "The choice of license will depend on your business specific needs and the business activities you will be conducting.": "The choice of license will depend on your business specific needs and the business activities you will be conducting.",
    "Decide on the place of registration": "Decide on the place of registration",
    "There are 3 main jurisdictions in the UAE: Mainland, Free zone, Offshore.": "There are 3 main jurisdictions in the UAE: Mainland, Free zone, Offshore.",
    "Get a list of requirements and approvals": "Get a list of requirements and approvals",
    "Depending on your business, obtaining special licenses and permissions from the relevant Emirates authorities may be required.": "Depending on your business, obtaining special licenses and permissions from the relevant Emirates authorities may be required.",
    "Register your company and get the visa": "Register your company and get the visa",
    "Apply for company registration, pay the fees, and obtain the visa and work permits for you and your employees.": "Apply for company registration, pay the fees, and obtain the visa and work permits for you and your employees.",
    "Open a bank account": "Open a bank account",
    "Once you have all the incorporation documents in hand, apply for personal or corporate bank accounts and get started!": "Once you have all the incorporation documents in hand, apply for personal or corporate bank accounts and get started!",
    "Start your business in the UAE free zones": "Start your business in the UAE free zones",
    "There are over 40 different freezones in the UAE to match all business needs": "There are over 40 different freezones in the UAE to match all business needs",
    "DMCC": "DMCC",
    "Dubai Multi Commodities Center": "Dubai Multi Commodities Center",
    "Dubai South Free Zone": "Dubai South Free Zone",
    "(ex. DWC)": "(ex. DWC)",
    "DTEC": "DTEC",
    "Dubai Technology Entrepreneur Center": "Dubai Technology Entrepreneur Center",
    "DAFZA": "DAFZA",
    "Dubai Airport Free Zone": "Dubai Airport Free Zone",
    "IFZA": "IFZA",
    "International Free Zone Authority": "International Free Zone Authority",
    "DSO": "DSO",
    "Dubai Silicon Oasis": "Dubai Silicon Oasis",
    "UAE TAXes": "UAE TAXes",
    "Find out essential details on UAE tax regulations": "Find out essential details on UAE tax regulations",
    "Corporate tax 9%": "Corporate tax 9%",
    "Corporate tax in the UAE is just 9%. All UAE companies need to register with the FTA and submit annual tax returns.": "Corporate tax in the UAE is just 9%. All UAE companies need to register with the FTA and submit annual tax returns.",
    "VAT": "VAT",
    "VAT in the UAE is one of the world's lowest - only 5%. Businesses with an annual revenue exceeding 375,000 AED are required to register for VAT with the FTA.": "VAT in the UAE is one of the world's lowest - only 5%. Businesses with an annual revenue exceeding 375,000 AED are required to register for VAT with the FTA.",
    "Zero personal TAX // Exemption certificate": "Zero personal TAX // Exemption certificate",
    "There is no personal income tax in the UAE, maintaining the country's appeal as a tax-friendly environment for individuals.": "There is no personal income tax in the UAE, maintaining the country's appeal as a tax-friendly environment for individuals.",
    "Dubai trade license": "Dubai trade license",
    "Compare the available business licenses and choose the one matching your needs": "Compare the available business licenses and choose the one matching your needs",
    "E-commerce license": "E-commerce license",
    "Transform your digital business ideas into reality with an E-Commerce License in the UAE": "Transform your digital business ideas into reality with an E-Commerce License in the UAE",
    "Beauty salon license": "Beauty salon license",
    "Embark on a beauty entrepreneur journey in the UAE by obtaining a Beauty Salon License": "Embark on a beauty entrepreneur journey in the UAE by obtaining a Beauty Salon License",
    "Car lease license": "Car lease license",
    "Enter the automotive market with a Car Lease License in the UAE, providing flexible and reliable vehicle leasing options.": "Enter the automotive market with a Car Lease License in the UAE, providing flexible and reliable vehicle leasing options.",
    "Become the UAE resident": "Become the UAE resident",
    "Apply for the UAE residence visa and enjoy all the benefits": "Apply for the UAE residence visa and enjoy all the benefits",
    "Golden visa": "Golden visa",
    "Prestigious 10-year visa": "Prestigious 10-year visa",
    "Real estate investor visa": "Real estate investor visa",
    "Invest in UAE real estate from AED 750,000": "Invest in UAE real estate from AED 750,000",
    "Partner visa": "Partner visa",
    "Elevate your business in the UAE": "Elevate your business in the UAE",
    "Open bank account in the UAE": "Open bank account in the UAE",
    "Learn about bank account types, terms, and requirements": "Learn about bank account types, terms, and requirements",
    "Corporate bank account": "Corporate bank account",
    "Establish a strong financial foundation for your business and grow your business domestically and internationally": "Establish a strong financial foundation for your business and grow your business domestically and internationally",
    "Resident bank account": "Resident bank account",
    "Manage your finances in a stable economic environment, making both local and international transactions with ease": "Manage your finances in a stable economic environment, making both local and international transactions with ease",
    "Non resident account": "Non resident account",
    "Access banking services, conduct financial transactions, and secure your savings without the requirement of residency": "Access banking services, conduct financial transactions, and secure your savings without the requirement of residency",
    "Learn more": "Learn more",
    "Apply now": "Apply now",
    "Watch Our Presentation": "Watch Our Presentation"
};
