// French translations
window.translations.fr = {
    "Business Setup in Dubai, Company Formation in UAE": "Création d'entreprise à Dubaï, constitution de société aux ÉAU",
    "Starting from 5,500 AED | Registration 1 day | Guaranteed bank account": "À partir de 5 500 AED | Enregistrement 1 jour | Compte bancaire garanti",
    "Get a Free Consultation": "Obtenir une consultation gratuite",
    "Our Services": "Nos services",
    "Company Formation": "Création de société",
    "Free Zone Setup": "Création de zone franche",
    "Mainland Company Setup": "Création de société continentale",
    "Offshore Company Setup": "Création de société offshore",
    "Visa Services": "Services de visa",
    "Bank Account Opening": "Ouverture de compte bancaire",
    "Learn More": "En savoir plus",
    "Fill out the form to contact an expert": "Remplissez le formulaire pour contacter un expert",
    "Your Name": "Votre nom",
    "Your Email": "Votre adresse e-mail",
    "Your Phone Number": "Votre numéro de téléphone",
    "Your Message": "Votre message",
    "Submit": "Soumettre",
    "UAE Business Setup Process": "Processus de création d'entreprise aux ÉAU",
    "Learn about the essential steps to establish your company in the UAE": "Découvrez les étapes essentielles pour créer votre entreprise aux ÉAU",
    "Choose the correct activity": "Choisissez la bonne activité",
    "The choice of license will depend on your business specific needs and the business activities you will be conducting.": "Le choix de la licence dépendra des besoins spécifiques de votre entreprise et des activités commerciales que vous exercerez.",
    "Decide on the place of registration": "Décidez du lieu d'enregistrement",
    "There are 3 main jurisdictions in the UAE: Mainland, Free zone, Offshore.": "Il existe 3 principales juridictions aux ÉAU : continentale, zone franche et offshore.",
    "Get a list of requirements and approvals": "Obtenez une liste des exigences et des approbations",
    "Depending on your business, obtaining special licenses and permissions from the relevant Emirates authorities may be required.": "Selon votre entreprise, l'obtention de licences et d'autorisations spéciales auprès des autorités compétentes des Émirats peut être nécessaire.",
    "Register your company and get the visa": "Enregistrez votre entreprise et obtenez le visa",
    "Apply for company registration, pay the fees, and obtain the visa and work permits for you and your employees.": "Demandez l'enregistrement de la société, payez les frais et obtenez le visa et les permis de travail pour vous et vos employés.",
    "Open a bank account": "Ouvrez un compte bancaire",
    "Once you have all the incorporation documents in hand, apply for personal or corporate bank accounts and get started!": "Une fois que vous avez tous les documents constitutifs en main, demandez l'ouverture de comptes bancaires personnels ou professionnels et lancez-vous !",
    "Start your business in the UAE free zones": "Démarrez votre entreprise dans les zones franches des ÉAU",
    "There are over 40 different freezones in the UAE to match all business needs": "Il existe plus de 40 zones franches différentes aux ÉAU pour répondre à tous les besoins des entreprises",
    "DMCC": "DMCC",
    "Dubai Multi Commodities Center": "Centre de commerce multi-matières premières de Dubaï",
    "Dubai South Free Zone": "Zone franche de Dubaï Sud",
    "(ex. DWC)": "(ex. DWC)",
    "DTEC": "DTEC",
    "Dubai Technology Entrepreneur Center": "Centre d'entrepreneuriat technologique de Dubaï",
    "DAFZA": "DAFZA",
    "Dubai Airport Free Zone": "Zone franche de l'aéroport de Dubaï",
    "IFZA": "IFZA",
    "International Free Zone Authority": "Autorité internationale de la zone franche",
    "DSO": "DSO",
    "Dubai Silicon Oasis": "Oasis de silicium de Dubaï",
    "UAE TAXes": "TAXES DES ÉAU",
    "Find out essential details on UAE tax regulations": "Découvrez les détails essentiels sur la réglementation fiscale des ÉAU",
    "Corporate tax 9%": "Impôt sur les sociétés 9 %",
    "Corporate tax in the UAE is just 9%. All UAE companies need to register with the FTA and submit annual tax returns.": "L'impôt sur les sociétés aux ÉAU n'est que de 9 %. Toutes les sociétés des ÉAU doivent s'inscrire auprès de la FTA et soumettre des déclarations fiscales annuelles.",
    "VAT": "TVA",
    "VAT in the UAE is one of the world's lowest - only 5%. Businesses with an annual revenue exceeding 375,000 AED are required to register for VAT with the FTA.": "La TVA aux ÉAU est l'une des plus basses au monde : seulement 5 %. Les entreprises dont le chiffre d'affaires annuel dépasse 375 000 AED sont tenues de s'inscrire à la TVA auprès de la FTA.",
    "Zero personal TAX // Exemption certificate": "Zéro impôt sur le revenu des personnes physiques // Certificat d'exemption",
    "There is no personal income tax in the UAE, maintaining the country's appeal as a tax-friendly environment for individuals.": "Il n'y a pas d'impôt sur le revenu des personnes physiques aux ÉAU, ce qui maintient l'attrait du pays en tant qu'environnement fiscalement favorable pour les particuliers.",
    "Dubai trade license": "Licence commerciale de Dubaï",
    "Compare the available business licenses and choose the one matching your needs": "Comparez les licences commerciales disponibles et choisissez celle qui correspond à vos besoins",
    "E-commerce license": "Licence de commerce électronique",
    "Transform your digital business ideas into reality with an E-Commerce License in the UAE": "Transformez vos idées commerciales numériques en réalité grâce à une licence de commerce électronique aux ÉAU",
    "Beauty salon license": "Licence de salon de beauté",
    "Embark on a beauty entrepreneur journey in the UAE by obtaining a Beauty Salon License": "Embarquez pour un voyage d'entrepreneur en beauté aux ÉAU en obtenant une licence de salon de beauté",
    "Car lease license": "Licence de location de voiture",
    "Enter the automotive market with a Car Lease License in the UAE, providing flexible and reliable vehicle leasing options.": "Entrez sur le marché automobile avec une licence de location de voiture aux ÉAU, offrant des options de location de véhicules flexibles et fiables.",
    "Become the UAE resident": "Devenez résident des ÉAU",
    "Apply for the UAE residence visa and enjoy all the benefits": "Demandez le visa de résidence des ÉAU et profitez de tous les avantages",
    "Golden visa": "Visa doré",
    "Prestigious 10-year visa": "Visa prestigieux de 10 ans",
    "Real estate investor visa": "Visa d'investisseur immobilier",
    "Invest in UAE real estate from AED 750,000": "Investissez dans l'immobilier des ÉAU à partir de 750 000 AED",
    "Partner visa": "Visa de partenaire",
    "Elevate your business in the UAE": "Développez votre entreprise aux ÉAU",
    "Open bank account in the UAE": "Ouvrez un compte bancaire aux ÉAU",
    "Learn about bank account types, terms, and requirements": "Découvrez les types de comptes bancaires, les conditions et les exigences",
    "Corporate bank account": "Compte bancaire d'entreprise",
    "Establish a strong financial foundation for your business and grow your business domestically and internationally": "Établissez une base financière solide pour votre entreprise et développez votre activité au niveau national et international",
    "Resident bank account": "Compte de résident",
    "Manage your finances in a stable economic environment, making both local and international transactions with ease": "Gérez vos finances dans un environnement économique stable, en effectuant facilement des transactions locales et internationales",
    "Non resident account": "Compte non-résident",
    "Access banking services, conduct financial transactions, and secure your savings without the requirement of residency": "Accédez aux services bancaires, effectuez des transactions financières et sécurisez votre épargne sans obligation de résidence",
    "Learn more": "En savoir plus",
    "Apply now": "Postuler maintenant",
    "Watch Our Presentation": "Regardez notre présentation"
};
