// Russian translations
window.translations.ru = {
    "Business Setup in Dubai, Company Formation in UAE": "Создание бизнеса в Дубае, создание компании в ОАЭ",
    "Starting from 5,500 AED | Registration 1 day | Guaranteed bank account": "От 5 500 дирхамов ОАЭ | Регистрация 1 день | Гарантированный банковский счет",
    "Get a Free Consultation": "Получите бесплатную консультацию",
    "Our Services": "Наши услуги",
    "Company Formation": "Создание компании",
    "Free Zone Setup": "Создание свободной зоны",
    "Mainland Company Setup": "Создание компании на материке",
    "Offshore Company Setup": "Создание оффшорной компании",
    "Visa Services": "Визовые услуги",
    "Bank Account Opening": "Открытие банковского счета",
    "Learn More": "Узнать больше",
    "Fill out the form to contact an expert": "Заполните форму, чтобы связаться с экспертом",
    "Your Name": "Ваше имя",
    "Your Email": "Ваш адрес электронной почты",
    "Your Phone Number": "Ваш номер телефона",
    "Your Message": "Ваше сообщение",
    "Submit": "Отправить",
    "UAE Business Setup Process": "Процесс создания бизнеса в ОАЭ",
    "Learn about the essential steps to establish your company in the UAE": "Узнайте об основных шагах по созданию вашей компании в ОАЭ",
    "Choose the correct activity": "Выберите правильный вид деятельности",
    "The choice of license will depend on your business specific needs and the business activities you will be conducting.": "Выбор лицензии будет зависеть от конкретных потребностей вашего бизнеса и видов деятельности, которые вы будете осуществлять.",
    "Decide on the place of registration": "Определитесь с местом регистрации",
    "There are 3 main jurisdictions in the UAE: Mainland, Free zone, Offshore.": "В ОАЭ есть 3 основные юрисдикции: материк, свободная зона, оффшор.",
    "Get a list of requirements and approvals": "Получите список требований и разрешений",
    "Depending on your business, obtaining special licenses and permissions from the relevant Emirates authorities may be required.": "В зависимости от вашего бизнеса может потребоваться получение специальных лицензий и разрешений от соответствующих органов власти Эмиратов.",
    "Register your company and get the visa": "Зарегистрируйте свою компанию и получите визу",
    "Apply for company registration, pay the fees, and obtain the visa and work permits for you and your employees.": "Подайте заявку на регистрацию компании, оплатите сборы и получите визу и разрешения на работу для себя и своих сотрудников.",
    "Open a bank account": "Откройте банковский счет",
    "Once you have all the incorporation documents in hand, apply for personal or corporate bank accounts and get started!": "Как только у вас будут все учредительные документы, подайте заявку на открытие личных или корпоративных банковских счетов и начинайте работу!",
    "Start your business in the UAE free zones": "Начните свой бизнес в свободных зонах ОАЭ",
    "There are over 40 different freezones in the UAE to match all business needs": "В ОАЭ насчитывается более 40 различных свободных зон, отвечающих всем потребностям бизнеса",
    "DMCC": "DMCC",
    "Dubai Multi Commodities Center": "Многопрофильный товарный центр Дубая",
    "Dubai South Free Zone": "Свободная зона Дубай Юг",
    "(ex. DWC)": "(ранее DWC)",
    "DTEC": "DTEC",
    "Dubai Technology Entrepreneur Center": "Технологический предпринимательский центр Дубая",
    "DAFZA": "DAFZA",
    "Dubai Airport Free Zone": "Свободная зона аэропорта Дубая",
    "IFZA": "IFZA",
    "International Free Zone Authority": "Международное управление свободной зоны",
    "DSO": "DSO",
    "Dubai Silicon Oasis": "Дубайский кремниевый оазис",
    "UAE TAXes": "НАЛОГИ ОАЭ",
    "Find out essential details on UAE tax regulations": "Узнайте важные детали о налоговом законодательстве ОАЭ",
    "Corporate tax 9%": "Корпоративный налог 9%",
    "Corporate tax in the UAE is just 9%. All UAE companies need to register with the FTA and submit annual tax returns.": "Корпоративный налог в ОАЭ составляет всего 9%. Все компании ОАЭ должны зарегистрироваться в FTA и подавать годовые налоговые декларации.",
    "VAT": "НДС",
    "VAT in the UAE is one of the world's lowest - only 5%. Businesses with an annual revenue exceeding 375,000 AED are required to register for VAT with the FTA.": "НДС в ОАЭ является одним из самых низких в мире - всего 5%. Предприятия с годовой выручкой более 375 000 дирхамов ОАЭ обязаны зарегистрироваться по НДС в FTA.",
    "Zero personal TAX // Exemption certificate": "Нулевой личный налог // Сертификат об освобождении",
    "There is no personal income tax in the UAE, maintaining the country's appeal as a tax-friendly environment for individuals.": "В ОАЭ нет налога на личный доход, что поддерживает привлекательность страны как благоприятной для налогообложения среды для частных лиц.",
    "Dubai trade license": "Торговая лицензия Дубая",
    "Compare the available business licenses and choose the one matching your needs": "Сравните доступные бизнес-лицензии и выберите ту, которая соответствует вашим потребностям",
    "E-commerce license": "Лицензия на электронную коммерцию",
    "Transform your digital business ideas into reality with an E-Commerce License in the UAE": "Превратите свои цифровые бизнес-идеи в реальность с помощью лицензии на электронную коммерцию в ОАЭ",
    "Beauty salon license": "Лицензия на салон красоты",
    "Embark on a beauty entrepreneur journey in the UAE by obtaining a Beauty Salon License": "Отправьтесь в путешествие в качестве предпринимателя в сфере красоты в ОАЭ, получив лицензию на салон красоты",
    "Car lease license": "Лицензия на аренду автомобилей",
    "Enter the automotive market with a Car Lease License in the UAE, providing flexible and reliable vehicle leasing options.": "Выйдите на автомобильный рынок с лицензией на аренду автомобилей в ОАЭ, предоставляя гибкие и надежные варианты аренды автомобилей.",
    "Become the UAE resident": "Станьте резидентом ОАЭ",
    "Apply for the UAE residence visa and enjoy all the benefits": "Подайте заявку на получение резидентской визы ОАЭ и пользуйтесь всеми преимуществами",
    "Golden visa": "Золотая виза",
    "Prestigious 10-year visa": "Престижная 10-летняя виза",
    "Real estate investor visa": "Виза инвестора в недвижимость",
    "Invest in UAE real estate from AED 750,000": "Инвестируйте в недвижимость ОАЭ от 750 000 дирхамов ОАЭ",
    "Partner visa": "Партнерская виза",
    "Elevate your business in the UAE": "Поднимите свой бизнес в ОАЭ",
    "Open bank account in the UAE": "Откройте банковский счет в ОАЭ",
    "Learn about bank account types, terms, and requirements": "Узнайте о типах банковских счетов, условиях и требованиях",
    "Corporate bank account": "Корпоративный банковский счет",
    "Establish a strong financial foundation for your business and grow your business domestically and internationally": "Создайте прочную финансовую основу для своего бизнеса и развивайте свой бизнес внутри страны и за рубежом",
    "Resident bank account": "Счет резидента",
    "Manage your finances in a stable economic environment, making both local and international transactions with ease": "Управляйте своими финансами в стабильной экономической среде, легко совершая местные и международные транзакции",
    "Non resident account": "Счет нерезидента",
    "Access banking services, conduct financial transactions, and secure your savings without the requirement of residency": "Получите доступ к банковским услугам, осуществляйте финансовые транзакции и обеспечьте сохранность своих сбережений без требования резидентства",
    "Learn more": "Узнать больше",
    "Apply now": "Подать заявку",
    "Watch Our Presentation": "Посмотрите нашу презентацию",
    
    // Company Registration Section
    "Company Registration in Dubai": "Регистрация компании в Дубае - Начните свой бизнес сегодня",
    "Streamlined Company Registration in Dubai": "Упрощенная регистрация компании в Дубае",
    "Company Registration Description": "Когда дело касается регистрации компании в Дубае, Business Setup Solutions вам поможет. Наши эксперты проведут вас через весь процесс, обеспечивая соответствие вашего бизнеса всем местным нормам. Давайте начнем ваш бизнес сегодня!",
    "Company Registration Guide Title": "Регистрация компании в Дубае – Ваше пошаговое руководство",
    "Company Registration Guide Intro": "Начало бизнеса в Дубае – это увлекательное предприятие, но оно включает в себя ряд важных шагов и соблюдение местных правил. В Business Setup Solutions мы упрощаем процесс и проводим вас через каждый этап регистрации компании. Вот пошаговое руководство, которое поможет вам начать:",
    
    // New content placeholders
    "Registration Step 1": "Choose the Right Business Activity and Legal Structure",
    "Registration Step 2": "Select a Unique Company Name",
    "Registration Step 3": "Prepare the Required Documents",
    "Registration Step 4": "Determine Share Capital",
    "Registration Step 5": "Obtain Initial Approval",
    "Registration Step 6": "Legalize and Notarize Documents",
    "Registration Step 7": "Rent a Physical Office Space",
    "Registration Step 8": "Submit Documents and Fees",
    "Registration Step 9": "Wait for Approval",
    "Registration Step 10": "Receive the License",
    "Registration Step 11": "Comply with Ongoing Requirements",
    "Company Registration Conclusion": "Navigating the process of company registration in Dubai may seem complex, but with the guidance of Business Setup Solutions, it becomes a streamlined and efficient experience.",
    
    // Visa Processing Section
    "Dubai Visa Processing Title": "Dubai Visa Processing and PRO Services - Effortless and Efficient",
    "Dubai Visa Processing Subtitle": "Hassle-Free Visa Processing and PRO Services in Dubai",
    "Dubai Visa Processing Description": "Navigating Dubai's visa and government procedures is complex, but our dedicated PRO services team at Business Setup Solutions handles it all, ensuring your business runs smoothly.",
    "Visa Processing Guide Title": "Visa Processing and PRO Services in Dubai – Your Hassle-Free Solution",
    "Visa Processing Guide Intro": "Navigating the complexities of visas and government procedures in Dubai can be challenging.",
    
    // Banking Solutions Section
    "Banking Solutions Title": "Banking Solutions in Dubai - Secure Your Financial Future",
    "Banking Solutions Subtitle": "Comprehensive Banking Solutions Tailored for Your Business",
    "Banking Solutions Description": "Securing your financial future in Dubai is a breeze with our comprehensive banking solutions.",
    
    // Immigration Services Section
    "Immigration Services Title": "Immigration Services in Dubai - Making Relocation Effortless",
    "Immigration Services Description": "Whether you're an individual looking to relocate to Dubai or a business in need of immigration support for your employees, Business Setup Solutions offers comprehensive Immigration Services.",
    
    // Co-Working Space Section
    "Coworking Title": "Co-Working Space/Private Office",
    "Coworking Subtitle": "Elevate Your Work Experience – Co-Working and Private Offices",
    "Coworking Description": "The perfect workspace is the cornerstone of productivity. Business Setup Solutions offers modern co-working spaces and private offices in prime Dubai locations.",
    
    // VAT and Audit Section
    "VAT Audit Title": "VAT Registration and Annual Audit Services in Dubai",
    "VAT Audit Subtitle": "Stay Compliant – VAT and Annual Audit Services in Dubai",
    "VAT Audit Description": "Staying compliant with VAT regulations is imperative for your Dubai business.",
    
    // Corporate Advisory Section
    "Corporate Advisory Title": "Strategic Corporate Advisory Services in Dubai",
    "Corporate Advisory Subtitle": "Navigate Market Complexities with Our Corporate Advisory Services",
    "Corporate Advisory Description": "Rely on Business Setup Solutions for strategic business decisions."
};
