// Russian translations
window.translations.ru = {
    "Business Setup in Dubai, Company Formation in UAE": "Создание бизнеса в Дубае, создание компании в ОАЭ",
    "Starting from 5,500 AED | Registration 1 day | Guaranteed bank account": "От 5 500 дирхамов ОАЭ | Регистрация 1 день | Гарантированный банковский счет",
    "Get a Free Consultation": "Получите бесплатную консультацию",
    "Our Services": "Наши услуги",
    "Company Formation": "Создание компании",
    "Free Zone Setup": "Создание свободной зоны",
    "Mainland Company Setup": "Создание компании на материке",
    "Offshore Company Setup": "Создание оффшорной компании",
    "Visa Services": "Визовые услуги",
    "Bank Account Opening": "Открытие банковского счета",
    "Learn More": "Узнать больше",
    "Fill out the form to contact an expert": "Заполните форму, чтобы связаться с экспертом",
    "Your Name": "Ваше имя",
    "Your Email": "Ваш адрес электронной почты",
    "Your Phone Number": "Ваш номер телефона",
    "Your Message": "Ваше сообщение",
    "Submit": "Отправить",
    "UAE Business Setup Process": "Процесс создания бизнеса в ОАЭ",
    "Learn about the essential steps to establish your company in the UAE": "Узнайте об основных шагах по созданию вашей компании в ОАЭ",
    "Choose the correct activity": "Выберите правильный вид деятельности",
    "The choice of license will depend on your business specific needs and the business activities you will be conducting.": "Выбор лицензии будет зависеть от конкретных потребностей вашего бизнеса и видов деятельности, которые вы будете осуществлять.",
    "Decide on the place of registration": "Определитесь с местом регистрации",
    "There are 3 main jurisdictions in the UAE: Mainland, Free zone, Offshore.": "В ОАЭ есть 3 основные юрисдикции: материк, свободная зона, оффшор.",
    "Get a list of requirements and approvals": "Получите список требований и разрешений",
    "Depending on your business, obtaining special licenses and permissions from the relevant Emirates authorities may be required.": "В зависимости от вашего бизнеса может потребоваться получение специальных лицензий и разрешений от соответствующих органов власти Эмиратов.",
    "Register your company and get the visa": "Зарегистрируйте свою компанию и получите визу",
    "Apply for company registration, pay the fees, and obtain the visa and work permits for you and your employees.": "Подайте заявку на регистрацию компании, оплатите сборы и получите визу и разрешения на работу для себя и своих сотрудников.",
    "Open a bank account": "Откройте банковский счет",
    "Once you have all the incorporation documents in hand, apply for personal or corporate bank accounts and get started!": "Как только у вас будут все учредительные документы, подайте заявку на открытие личных или корпоративных банковских счетов и начинайте работу!",
    "Start your business in the UAE free zones": "Начните свой бизнес в свободных зонах ОАЭ",
    "There are over 40 different freezones in the UAE to match all business needs": "В ОАЭ насчитывается более 40 различных свободных зон, отвечающих всем потребностям бизнеса",
    "DMCC": "DMCC",
    "Dubai Multi Commodities Center": "Многопрофильный товарный центр Дубая",
    "Dubai South Free Zone": "Свободная зона Дубай Юг",
    "(ex. DWC)": "(ранее DWC)",
    "DTEC": "DTEC",
    "Dubai Technology Entrepreneur Center": "Технологический предпринимательский центр Дубая",
    "DAFZA": "DAFZA",
    "Dubai Airport Free Zone": "Свободная зона аэропорта Дубая",
    "IFZA": "IFZA",
    "International Free Zone Authority": "Международное управление свободной зоны",
    "DSO": "DSO",
    "Dubai Silicon Oasis": "Дубайский кремниевый оазис",
    "UAE TAXes": "НАЛОГИ ОАЭ",
    "Find out essential details on UAE tax regulations": "Узнайте важные детали о налоговом законодательстве ОАЭ",
    "Corporate tax 9%": "Корпоративный налог 9%",
    "Corporate tax in the UAE is just 9%. All UAE companies need to register with the FTA and submit annual tax returns.": "Корпоративный налог в ОАЭ составляет всего 9%. Все компании ОАЭ должны зарегистрироваться в FTA и подавать годовые налоговые декларации.",
    "VAT": "НДС",
    "VAT in the UAE is one of the world's lowest - only 5%. Businesses with an annual revenue exceeding 375,000 AED are required to register for VAT with the FTA.": "НДС в ОАЭ является одним из самых низких в мире - всего 5%. Предприятия с годовой выручкой более 375 000 дирхамов ОАЭ обязаны зарегистрироваться по НДС в FTA.",
    "Zero personal TAX // Exemption certificate": "Нулевой личный налог // Сертификат об освобождении",
    "There is no personal income tax in the UAE, maintaining the country's appeal as a tax-friendly environment for individuals.": "В ОАЭ нет налога на личный доход, что поддерживает привлекательность страны как благоприятной для налогообложения среды для частных лиц.",
    "Dubai trade license": "Торговая лицензия Дубая",
    "Compare the available business licenses and choose the one matching your needs": "Сравните доступные бизнес-лицензии и выберите ту, которая соответствует вашим потребностям",
    "E-commerce license": "Лицензия на электронную коммерцию",
    "Transform your digital business ideas into reality with an E-Commerce License in the UAE": "Превратите свои цифровые бизнес-идеи в реальность с помощью лицензии на электронную коммерцию в ОАЭ",
    "Beauty salon license": "Лицензия на салон красоты",
    "Embark on a beauty entrepreneur journey in the UAE by obtaining a Beauty Salon License": "Отправьтесь в путешествие в качестве предпринимателя в сфере красоты в ОАЭ, получив лицензию на салон красоты",
    "Car lease license": "Лицензия на аренду автомобилей",
    "Enter the automotive market with a Car Lease License in the UAE, providing flexible and reliable vehicle leasing options.": "Выйдите на автомобильный рынок с лицензией на аренду автомобилей в ОАЭ, предоставляя гибкие и надежные варианты аренды автомобилей.",
    "Become the UAE resident": "Станьте резидентом ОАЭ",
    "Apply for the UAE residence visa and enjoy all the benefits": "Подайте заявку на получение резидентской визы ОАЭ и пользуйтесь всеми преимуществами",
    "Golden visa": "Золотая виза",
    "Prestigious 10-year visa": "Престижная 10-летняя виза",
    "Real estate investor visa": "Виза инвестора в недвижимость",
    "Invest in UAE real estate from AED 750,000": "Инвестируйте в недвижимость ОАЭ от 750 000 дирхамов ОАЭ",
    "Partner visa": "Партнерская виза",
    "Elevate your business in the UAE": "Поднимите свой бизнес в ОАЭ",
    "Open bank account in the UAE": "Откройте банковский счет в ОАЭ",
    "Learn about bank account types, terms, and requirements": "Узнайте о типах банковских счетов, условиях и требованиях",
    "Corporate bank account": "Корпоративный банковский счет",
    "Establish a strong financial foundation for your business and grow your business domestically and internationally": "Создайте прочную финансовую основу для своего бизнеса и развивайте свой бизнес внутри страны и за рубежом",
    "Resident bank account": "Счет резидента",
    "Manage your finances in a stable economic environment, making both local and international transactions with ease": "Управляйте своими финансами в стабильной экономической среде, легко совершая местные и международные транзакции",
    "Non resident account": "Счет нерезидента",
    "Access banking services, conduct financial transactions, and secure your savings without the requirement of residency": "Получите доступ к банковским услугам, осуществляйте финансовые транзакции и обеспечьте сохранность своих сбережений без требования резидентства",
    "Learn more": "Узнать больше",
    "Apply now": "Подать заявку",
    "Watch Our Presentation": "Посмотрите нашу презентацию"
};
